### PR TITLE
Tome of Fire boosts Trident of the Swamp DPS ... (#88)

### LINKED ISSUE #88: Tome of Fire boosts Trident of the Swamp DPS by 3 points over Book of Darkness, but Tome of Fire shouldn't boost Trident damage
I believe the DPS is incorrectly calculating a DPS boost when using the Tome of Fire with the Trident of the Swamp in this specific scenario.

Here are screen shots of how each section is configured without using the tome of fire, as well as a screen shot of the DPS.

### Equipment:
image

### NPC Stats
image

### Skills
image

### Prayer
image

### Result
image

When I take the same setup but switch out the Book of Darkness with a Tome of Fire, the DPS will change from 5.8 to 8.7. That's an almost 3 DPS boost. The Tome of Fire's boost should not work with the Trident of the Swamp.

### Equipment:

image

### Result
image

### PR DESCRIPTION
**Pull request by brickinthewall4138**
* calc: Ensure player is either autocasting or manually casting before applying tome bonuses

Closes #88

### CODE REVIEW

**Comment by LlemonDuck** [comment]
I'm not sure I understand what the original bug here was. It seems the check in compute should check whether the spell is being cast. Is the spell field not cleared when using a powered staff?

Also, make sure you update the unit test to check for this behaviour.

**Comment by brickinthewall4138** [comment]
That's exactly right, the spell field isn't cleared. It's easy enough to check in client (select target, trident+attack style, and magic level -> observe trident max hit -> equip tome of fire and choose a fire spell -> switch back to previous attack style -> observe max hit has increased).
I added a guard for it in this case rather than clearing it properly because I'm not familiar enough with the project to know if it's a good idea to clear that spell field, do you think it could be a problem elsewhere?

Right, I'll look into the unit tests in a bit.

**Comment by LlemonDuck** [comment]
Adding a guard is indeed the correct approach, although it might also be good to add a clear in the ComputeContext builders. If combat style is not auto/manual-cast, don't set spell. Ideally, guarded in both places, but the one in CC doesn't need to be included here if you'd rather keep it simple.

**Comment by brickinthewall4138** [comment]
> Adding a guard is indeed the correct approach, although it might also be good to add a clear in the ComputeContext builders. If combat style is not auto/manual-cast, don't set spell. Ideally, guarded in both places, but the one in CC doesn't need to be included here if you'd rather keep it simple.

The problem is there is no 'null' spell, and context.get() throws an exception if we were to 'clear' the spell field by setting it to null. After writing maybe 3 catch-except blocks in case the spell field has been set to null, I'm starting to think this isn't really a great idea and we should keep it at guarding against non-autocast/non-manual cast, your thoughts?

**Comment by LlemonDuck** [comment]
Yeah, just leave it out of this PR and I'll make a more global solution later using a SpellComputable.

**Review by LlemonDuck — APPROVED** [review]

**Pull request merged**
